export enum AuthActionTypes {
  START_LOGIN_USER = 'START_LOGIN_USER',
  LOGIN_USER_SUCCESSFUL = 'LOGIN_USER_SUCCESSFUL',
  LOGIN_USER_FAILED = 'LOGIN_USER_FAILED',

  START_LOGOUT_USER = 'START_LOGOUT_USER',
  LOGOUT_USER_SUCCESSFUL = 'LOGOUT_USER_SUCCESSFUL',
  LOGOUT_USER_FAILED = 'LOGOUT_USER_FAILED'
}
